server:
  port: 8081
spring:
  profiles: dev

  # 使用文件快的方式
---
server:
  port: 8083
spring:
  profiles: dev
---

---
server:
  port: 80
spring:
  profiles: prod
---
#
#person:
#  lastName : zhangsan
#  age : 18
#  boss : false
#  birth : 2017/12/12
#  maps : {k1,k2,k3}
#  lists:
#    - lisi
#    - zhaoliui
#  dog :
#    name : 小狗
#    age : 2